name: ocr_scanner
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5

  permission_handler: ^11.0.1
  tflite_v2: ^1.0.0
  path_provider: ^2.1.1
  path: ^1.8.3
  get: ^4.6.6
  google_mlkit_text_recognition: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/labels.txt
    - assets/model_unquant.tflite
